#spring:
##  security:
##    user:
##      name: admin
##      password: password
#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: localhost:9092

example:
  test:
    value: config-server-test-aaaaaaa